ControlFocus("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","C:\Users\shivam_kushwaha\eclipse-workspace\ShoppingPortal\src\resources\autoIt\SamsungTVSideView.jpg")
Sleep(3000)
ControlClick("Open","","Button1")