ControlFocus("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","D:\persistent system\mini project\Online Shopping Portal project files\ShoppingPortal-Java\src\resources\autoIt\SamsungTVFrontView.jpg")
Sleep(3000)
ControlClick("Open","","Button1")